### ISSUE TITLE
Syncing to AWS, 

### ISSUE THREAD

**Issue by shamca65** [suda/dvsync#2]
Setup the server on my localhost:
```
docker run --rm -e NGROK_AUTHTOKEN="<<my token in double quotes>>" \
  --mount source=wwwGems,target=/data,readonly \
  quay.io/suda/dvsync-server
```
🚀  Starting dvsync server...
🔑  Generating server RSA key...
🔑  Generating client RSA key...
⚡️  dvsync server is running! To sync, start the client with following environment variable set:

Used DVSYNC_TOKEN & setup server on my EC2:

```
docker run --rm -e DVSYNC_TOKEN="<<my DVSYNC_TOKEN>>" \
>   --mount source=wwwGems,target=/data \
>   quay.io/suda/dvsync-client

```
⚡️  dvsync client is connecting to 0.tcp.ngrok.io:10821
receiving incremental file list

sent 20 bytes  received 40 bytes  24.00 bytes/sec
total size is 0  speedup is 0.00

No data transfered.
Host's volume reports a size of > 1g (so there is data there...)

Thoughts? Did I mix up source & target between server & client?

Thanks!

**Comment by suda** [comment]
Hmm, it did send/receive data, so the network connection seems to be fine.
Can you try opening a shell in the server and client containers to list the contents like so:

```
docker run --rm -it -e NGROK_AUTHTOKEN="<<my token in double quotes>>" \
  --mount source=wwwGems,target=/data,readonly \
  --entrypoint=/bin/sh \
  quay.io/suda/dvsync-server

/ # ls -lha /data
```

**Comment by shamca65** [comment]
This is the result:
➜  ~ docker exec -it ebc6cb8574b6 ls -lha /data
total 8
drwxr-xr-x    2 root     root        4.0K Mar 12 15:00 .
drwxr-xr-x    1 root     root        4.0K Mar 13 18

**Comment by shamca65** [comment]
Let me regenerate the volume. I suspect the error is between the keyboard and chair.

**Comment by shamca65** [comment]
Yep, your stuff is working excellently. My error. Too many docker windows.

Thanks!

BTW - on your readme.md - the word 'docker' is missing from the server start up command.
Have a great day and thank you.

**Comment by suda** [comment]
Glad it's working :) I added missing `docker` to the readme, thanks for spotting the error!
